name: Deploy Documentation to GitHub Pages

permissions:
  contents: read
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build Documentation with DocFX
        run: docfx docfx.json

      - name: Upload Artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
