name: Publish NuGet Packages

permissions:
  contents: read
  packages: write
  id-token: write

on:
  release:
    types: [published]
  push:
    branches:
      - develop
      - main
      - "feature/*"

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Update Version in Directory.Build.props
        id: set-version
        run: |
          BASE_VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' Directory.Build.props)

          if [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ github.ref_name }}" == "develop" ]]; then
              BUILD_VERSION="${BASE_VERSION}-alpha.${{ github.run_number }}"
            elif [[ "${{ github.ref_name }}" =~ ^feature/ ]]; then
              BUILD_VERSION="${BASE_VERSION}-alpha.${{ github.run_number }}"
            else
              echo "Unknown branch for alpha versioning: ${{ github.ref_name }}"
              exit 1
            fi
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            BUILD_VERSION="${BASE_VERSION}"
          else
            echo "Unknown context for versioning: ${{ github.event_name }}"
            exit 1
          fi
          sed -i "s|<Version>.*</Version>|<Version>${BUILD_VERSION}</Version>|" Directory.Build.props
          echo "Updated Directory.Build.props with version: $BUILD_VERSION"

      - name: Restore NuGet packages
        run: dotnet restore ./BytLabs.BackendPackages.sln

      - name: Build and Pack NuGet Packages
        run: |
          search_directory="./src"
          find "$search_directory" -name "*.csproj" | while IFS= read -r proj; do
              if [[ "$proj" == *"Test.csproj" ]]; then
                  echo "Skipping test project: $proj"
                  continue
              fi
              echo "Building and packing project: $proj"
              dotnet pack "$proj" --configuration Release --output ./nuget-packages
          done

      - name: Publish NuGet Packages
        run: |
          search_directory="./nuget-packages"
          find "$search_directory" -name "*.nupkg" | while IFS= read -r pkg; do
              echo "Pushing package: $pkg"
              dotnet nuget push "$pkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
              dotnet nuget push "$pkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          done

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
